/**
 * Generates a TypeScript file that statically imports all spec files
 * for use in React Native (which cannot use dynamic imports).
 *
 * Usage:
 *   npx ts-node src/common/tools/gen_rn_specs.ts [--suite webgpu] [--out path/to/output.ts]
 *
 * This will generate a file like:
 *
 *   import * as spec0 from '../../webgpu/api/operation/adapter/info.spec.js';
 *   import * as spec1 from '../../webgpu/api/operation/adapter/requestAdapter.spec.js';
 *   ...
 *   export const allSpecs = new Map([
 *     ['webgpu', [
 *       { path: ['api', 'operation', 'adapter', 'info'], spec: spec0 },
 *       { path: ['api', 'operation', 'adapter', 'requestAdapter'], spec: spec1 },
 *       ...
 *     ]],
 *   ]);
 */

import * as fs from 'fs';
import * as path from 'path';

const specFileSuffix = '.spec.ts';

async function crawlSpecFiles(dir: string): Promise<string[]> {
  const results: string[] = [];

  async function crawl(currentDir: string): Promise<void> {
    const entries = await fs.promises.readdir(currentDir, { withFileTypes: true });

    for (const entry of entries) {
      const fullPath = path.join(currentDir, entry.name);

      if (entry.isDirectory()) {
        await crawl(fullPath);
      } else if (entry.isFile() && entry.name.endsWith(specFileSuffix)) {
        results.push(fullPath);
      }
    }
  }

  await crawl(dir);
  return results.sort();
}

interface GenerateOptions {
  /** Suite name (e.g., 'webgpu') */
  suite: string;
  /** Root directory of the CTS source */
  rootDir: string;
  /** Output file path */
  outputPath: string;
  /** Import path prefix (for adjusting relative imports) */
  importPrefix?: string;
}

async function generateSpecsFile(options: GenerateOptions): Promise<void> {
  const { suite, rootDir, outputPath, importPrefix = '../..' } = options;

  const suiteDir = path.join(rootDir, 'src', suite);
  if (!fs.existsSync(suiteDir)) {
    throw new Error(`Suite directory not found: ${suiteDir}`);
  }

  const specFiles = await crawlSpecFiles(suiteDir);

  console.log(`Found ${specFiles.length} spec files in ${suite}`);

  // Generate imports and entries
  const imports: string[] = [];
  const entries: string[] = [];

  specFiles.forEach((filePath, index) => {
    // Get path relative to suite dir
    const relativePath = path.relative(suiteDir, filePath);
    // Convert to path parts (without .spec.ts extension)
    const pathWithoutExt = relativePath.replace(/\.spec\.ts$/, '');
    const pathParts = pathWithoutExt.split(path.sep);

    // Import path (use .js extension for ESM compatibility)
    const importPath = `${importPrefix}/${suite}/${pathWithoutExt}.spec.js`;

    imports.push(`import * as spec${index} from '${importPath}';`);
    entries.push(`      { path: [${pathParts.map(p => `'${p}'`).join(', ')}], spec: spec${index} },`);
  });

  const output = `/**
 * Auto-generated file - DO NOT EDIT
 * Generated by: npx tsx src/common/tools/gen_rn_specs.ts
 *
 * This file statically imports all CTS spec files for React Native.
 */

import { AllSpecs, SpecEntry } from '../loader.js';

${imports.join('\n')}

const ${suite}Specs: SpecEntry[] = [
${entries.join('\n')}
];

export const allSpecs: AllSpecs = new Map([
  ['${suite}', ${suite}Specs],
]);

export default allSpecs;
`;

  // Ensure output directory exists
  const outputDir = path.dirname(outputPath);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(outputPath, output);
  console.log(`Generated: ${outputPath}`);
}

// CLI handling
async function main(): Promise<void> {
  const args = process.argv.slice(2);

  let suite = 'webgpu';
  let outputPath = 'src/common/runtime/rn/generated/all_specs.ts';
  let importPrefix = '../../..';

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--suite' && args[i + 1]) {
      suite = args[++i];
    } else if (args[i] === '--out' && args[i + 1]) {
      outputPath = args[++i];
    } else if (args[i] === '--import-prefix' && args[i + 1]) {
      importPrefix = args[++i];
    } else if (args[i] === '--help') {
      console.log(`
Usage: npx ts-node src/common/tools/gen_rn_specs.ts [options]

Options:
  --suite <name>         Suite to generate imports for (default: webgpu)
  --out <path>           Output file path (default: src/common/runtime/rn/generated/all_specs.ts)
  --import-prefix <path> Prefix for import paths (default: ../../..)
  --help                 Show this help message
`);
      process.exit(0);
    }
  }

  // Find root directory (where src/ is)
  let rootDir = process.cwd();
  if (!fs.existsSync(path.join(rootDir, 'src', suite))) {
    // Try going up one level
    rootDir = path.dirname(rootDir);
    if (!fs.existsSync(path.join(rootDir, 'src', suite))) {
      throw new Error(`Cannot find src/${suite} directory. Run from CTS root.`);
    }
  }

  await generateSpecsFile({
    suite,
    rootDir,
    outputPath: path.join(rootDir, outputPath),
    importPrefix,
  });
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
