name: GLSL CI

on:
  push:
    branches: [glsl-dependent]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "15.x"
      - run: npm ci
      - run: |
          npm test
          sed -i '/out\//d' .gitignore
          sed -i '/out-wpt\//d' .gitignore
      - run: |
          cat << EOF >> firebase.json
          {
            "hosting": {
              "public": ".",
              "ignore": [
                "firebase.json",
                "**/.*",
                "**/node_modules/**"
              ]
            }
          }
          EOF
          cat << EOF >> .firebaserc
          {
            "projects": {
              "default": "gpuweb-prs"
            }
          }
          EOF
      - id: deployment
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          expires: 30d
          channelId: live
