name: Push CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "15.x"
      - run: npm ci
      - run: |
          npm test
          mkdir deploy-build/
          cp -r README.md src out out-wpt out-standalone docs tools deploy-build/
          mkdir deploy-build/standalone
          cp standalone/index.html standalone/webgpu-logo-notext.svg deploy-build/standalone/
          cp -r standalone/third_party deploy-build/standalone/
      - uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          BRANCH: gh-pages
          FOLDER: deploy-build
          CLEAN: true
