name: Workflow CI

on:
  workflow_run:
    workflows:
      - "Pull Request CI"
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - run: |
          PR=$(curl https://api.github.com/search/issues?q=${{ github.event.workflow_run.head_sha }} |
          grep -Po "(?<=${{ github.event.workflow_run.repository.full_name }}\/pulls\/)\d*" | head -1)
          echo "PR=$PR" >> $GITHUB_ENV
      - run: |
          cat << EOF >> firebase.json
          {
            "hosting": {
              "public": ".",
              "ignore": [
                "firebase.json",
                "**/.*",
                "**/node_modules/**"
              ]
            }
          }
          EOF
          cat << EOF >> .firebaserc
          {
            "projects": {
              "default": "gpuweb-prs"
            }
          }
          EOF
      - id: deployment
        continue-on-error: true
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          expires: 30d
          channelId: cts-prs-${{ env.PR }}-${{ github.event.workflow_run.head_sha }}
      - uses: peter-evans/create-or-update-comment@v1
        continue-on-error: true
        if: ${{ steps.deployment.outcome == 'success' }}
        with:
          issue-number: ${{ env.PR }}
          body: |
            Previews, as seen at the time of posting this comment:
            [**Run this PR's tests live**](${{ steps.deployment.outputs.details_url }}/standalone/)
            <sub>${{ github.event.workflow_run.head_sha }}</sub>
            <!--
            pr;sha
            ${{ env.PR }};${{ github.event.workflow_run.head_sha }}
            -->
